language: python
python:
  - 3.8

services:
  - docker

install:
  - docker build -t pathogen-memo-pack . 
  - docker run -it -p 8080:8080 -p 5432:5432 -p 5000:5000 pathogen-memo-pack:latest

before_script:
  - pip install -r requirements.txt

script:
  - docker ps | grep -q pathogen-memo-pack
  - python tests.py