
import os 

SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL')

#SECRET_KEY = os.urandom(32)
SECRET_KEY = os.environ.get('SECRET_KEY')

SQLALCHEMY_TRACK_MODIFICATIONS = False

SEND_FILE_MAX_AGE_DEFAULT=0
